Fix Kotlin compilation errors in @react-native-menu/menu
The package has 'val' reassignment errors in MenuView.kt and
MenuViewManagerBase.kt. This patch fixes them by:

1. MenuView.kt - Use backing field instead of super property assignment
2. MenuViewManagerBase.kt - Use setter methods (setHitSlopRect, setOverflow)
   instead of direct property assignments

Fixes build errors:
- MenuView.kt:28 - 'val' cannot be reassigned
- MenuViewManagerBase.kt:126,128,209 - 'val' cannot be reassigned